app:
    resource: '@AppBundle/Controller/'
    type: annotation
eatit:
    resource: '@EatitAppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
