AppBundle\Entity\User:
    type: entity
    table: fos_user

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO   
        nickname:
            type: string
            length: 255        
            nullable: true
        firstname:
            type: string
            length: 255         
            nullable: true
        lastname:
            type: string
            length: 255         
            nullable: true
        image:
            type: string
            length: 2            
            nullable: strue
